name: Publish package to PyPI

on:
  push:
    tags: ['v*.*.*']

jobs:
  publish-package:
    name: Publish package to PyPI
    uses: githuib/base/.github/workflows/publish-to-pypi.yaml@master
    secrets: inherit
