name: Publish package to PyPI

on:
  push:
    tags: ['v*.*.*']

jobs:
  publish-package:
    name: Publish package to PyPI
    uses: githuib/base/.github/workflows/publish-to-pypi.yaml@master
    secrets: inherit
    permissions:
      contents: write  # to create release on github
#      id-token: write  # mandatory for Trusted Publishing
